apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
  labels:
    component: backend
    project: expense
    tier: app
data:
  DB_HOST: "mysql"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
  labels:
    component: backend
    project: expense
    tier: app
spec:
  selector:
    component: backend
    project: expense
    tier: app
  ports:
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # deployment labels
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: 2
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
  # This is pod definition
  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: app
    spec:
      containers:
      - name: backend
        image: satishbandi33/expense-backend:v1
        envFrom:
        - configMapRef:
            name: backend